# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ll_sum <- function(index, Zg1, Zg0, prior) {
    .Call('_tadaA_ll_sum', PACKAGE = 'tadaA', index, Zg1, Zg0, prior)
}

#' @export
cal1 <- function(x, selected_annotations, all_rr) {
    .Call('_tadaA_cal1', PACKAGE = 'tadaA', x, selected_annotations, all_rr)
}

#' @export
cal2 <- function(x) {
    .Call('_tadaA_cal2', PACKAGE = 'tadaA', x)
}

#' @export
sumall1 <- function(DATA, selected_annotations, all_rr) {
    .Call('_tadaA_sumall1', PACKAGE = 'tadaA', DATA, selected_annotations, all_rr)
}

#' @export
sumall0 <- function(DATA) {
    .Call('_tadaA_sumall0', PACKAGE = 'tadaA', DATA)
}

#' @export
post <- function(index, Zg1, Zg0, prior) {
    .Call('_tadaA_post', PACKAGE = 'tadaA', index, Zg1, Zg0, prior)
}

